# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(765, 638)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.marketView = QtGui.QWidget()
        self.marketView.setObjectName(_fromUtf8("marketView"))
        self.gridLayout_4 = QtGui.QGridLayout(self.marketView)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget_2 = QtGui.QTabWidget(self.marketView)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.digitalExchange = QtGui.QWidget()
        self.digitalExchange.setObjectName(_fromUtf8("digitalExchange"))
        self.gridLayout_6 = QtGui.QGridLayout(self.digitalExchange)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tableView = QtGui.QTableView(self.digitalExchange)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_5.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.digitalExchange, _fromUtf8(""))
        self.currencyExchange = QtGui.QWidget()
        self.currencyExchange.setObjectName(_fromUtf8("currencyExchange"))
        self.gridLayout_8 = QtGui.QGridLayout(self.currencyExchange)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.currencyExchange_plotTitle = QtGui.QLabel(self.currencyExchange)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.currencyExchange_plotTitle.setFont(font)
        self.currencyExchange_plotTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.currencyExchange_plotTitle.setObjectName(_fromUtf8("currencyExchange_plotTitle"))
        self.verticalLayout.addWidget(self.currencyExchange_plotTitle)
        self.currencyExchange_graphicsView = PlotWidget(self.currencyExchange)
        self.currencyExchange_graphicsView.setObjectName(_fromUtf8("currencyExchange_graphicsView"))
        self.verticalLayout.addWidget(self.currencyExchange_graphicsView)
        self.gridLayout_8.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.currencyExchange_tableView = QtGui.QTableView(self.currencyExchange)
        self.currencyExchange_tableView.setObjectName(_fromUtf8("currencyExchange_tableView"))
        self.gridLayout_7.addWidget(self.currencyExchange_tableView, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.currencyExchange, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.marketView, _fromUtf8(""))
        self.tradeView = QtGui.QWidget()
        self.tradeView.setObjectName(_fromUtf8("tradeView"))
        self.tabWidget.addTab(self.tradeView, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 765, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAccount = QtGui.QMenu(self.menubar)
        self.menuAccount.setObjectName(_fromUtf8("menuAccount"))
        self.menuBlockchain = QtGui.QMenu(self.menuAccount)
        self.menuBlockchain.setObjectName(_fromUtf8("menuBlockchain"))
        self.menuCoinbase = QtGui.QMenu(self.menuAccount)
        self.menuCoinbase.setObjectName(_fromUtf8("menuCoinbase"))
        self.menuCurrency_Exchange = QtGui.QMenu(self.menuAccount)
        self.menuCurrency_Exchange.setObjectName(_fromUtf8("menuCurrency_Exchange"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionLog_In = QtGui.QAction(MainWindow)
        self.actionLog_In.setObjectName(_fromUtf8("actionLog_In"))
        self.actionLog_In_2 = QtGui.QAction(MainWindow)
        self.actionLog_In_2.setObjectName(_fromUtf8("actionLog_In_2"))
        self.actionLog_In_3 = QtGui.QAction(MainWindow)
        self.actionLog_In_3.setObjectName(_fromUtf8("actionLog_In_3"))
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBlockchain.addAction(self.actionLog_In_3)
        self.menuCoinbase.addAction(self.actionLog_In_2)
        self.menuCurrency_Exchange.addAction(self.actionLog_In)
        self.menuAccount.addAction(self.menuBlockchain.menuAction())
        self.menuAccount.addAction(self.menuCoinbase.menuAction())
        self.menuAccount.addAction(self.menuCurrency_Exchange.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAccount.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.digitalExchange), _translate("MainWindow", "Digital Exchange", None))
        self.currencyExchange_plotTitle.setText(_translate("MainWindow", "Plot Title", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.currencyExchange), _translate("MainWindow", "Currency Exchange", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.marketView), _translate("MainWindow", "Market View", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tradeView), _translate("MainWindow", "Trade View", None))
        self.label.setText(_translate("MainWindow", "BitCurrency v0.0.1 - 8/29/15 - Sacha Best", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuAccount.setTitle(_translate("MainWindow", "Accounts", None))
        self.menuBlockchain.setTitle(_translate("MainWindow", "Blockchain", None))
        self.menuCoinbase.setTitle(_translate("MainWindow", "Coinbase", None))
        self.menuCurrency_Exchange.setTitle(_translate("MainWindow", "Currency Exchange", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionLog_In.setText(_translate("MainWindow", "Log In", None))
        self.actionLog_In_2.setText(_translate("MainWindow", "Log In", None))
        self.actionLog_In_3.setText(_translate("MainWindow", "Log In", None))

from pyqtgraph import PlotWidget
